version: '3.7'

services:
  traefik_base:
    image: traefik:v3.2.0
    ports:
      - 8080:80
    command:
      - "--configFile=/etc/traefik/config-static.yaml"
    volumes:
      - ./:/etc/traefik

  traefik:
    extends: traefik_base
    depends_on:
      - httpbin

  httpbin:
    image: mccutchen/go-httpbin:v2.9.0
    environment:
      - APP_NAME=httpbin
      - MAX_BODY_SIZE=15728640 # 15 MiB
    command: [ "/bin/go-httpbin", "-port", "8000" ]
    ports:
      - 8000:8000
